### ISSUE TITLE
cant find the link

### ISSUE THREAD

**Issue by SaraZaydan** [amitshekhariitbhu/Android-TensorFlow-Lite-Example#18]
https://letslearnai.com/2018/03/17/android-tensorflow-lite-machine-learning-example.html 
Im trying to reach this link but it looks that it has been deleted , can you give me another link to this article please.
Thank you in advanced

**Comment by amitshekhariitbhu** [comment]
Thanks for pointing it out. I am updating it. The correct link is: https://afteracademy.com/blog/android-tensorflow-lite-machine-learning-example
